### ISSUE TITLE
Documentation needed on quick-repeat-list

### ISSUE THREAD

**Issue by djsmith42** [allaud/quick-ng-repeat#1]
What is quick-repeat-list intended for? Does each of my quick-ng-repeat instances need a unique quick-repeat-list value?

**Comment by yeddu** [comment]
I want to repeat the hierarchical data using quick-ng-repeat. How can i do this?

**Comment by alirizwan** [comment]
<md-list-item quick-ng-repeat="(ticket in vmFilteredData | filter:vm.query)" quick-repeat-list="titems">

This is going on in: vm.FilteredData = $filter('filter')(vm.data, { CategoryId: vm.currentCategory.id });

All I get is one empty item. What could I be doing wrong here? Is it because of quick-repeat-list?
